stages:
  - sonarqube-check

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
    
sonarqube-analysis:
  stage: sonarqube-check
  image: 
    name: sonarsource/sonar-scanner-cli:latest
  script:
    - |
      # Всегда анализируем все файлы, но принудительно обновляем анализ
      sonar-scanner \
        -Dsonar.projectKey=testproject \
        -Dsonar.host.url=${SONAR_HOST_URL} \
        -Dsonar.token=${SONAR_TOKEN} \
        -Dsonar.sources=. \
        -Dsonar.inclusions=**/*.bsl,**/*.os \
        -Dsonar.language=bsl \
        -Dsonar.ssl.verify=false \
        -Dsonar.pullrequest.key=${CI_MERGE_REQUEST_IID} \
        -Dsonar.pullrequest.branch=${CI_COMMIT_REF_NAME} \
        -Dsonar.pullrequest.base=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} \
        -Dsonar.pullrequest.provider=gitlab \
        -Dsonar.pullrequest.gitlab.repositoryUrl=${CI_REPOSITORY_URL} \
        -Dsonar.pullrequest.gitlab.projectId=${CI_PROJECT_ID} \
        -Dsonar.pullrequest.gitlab.commitSha=${CI_COMMIT_SHA} \
        -Dsonar.pullrequest.gitlab.mergeRequestIid=${CI_MERGE_REQUEST_IID} \
        -Dsonar.qualitygate.wait=true \
        -Dsonar.qualitygate.timeout=600
        # ↓↓↓ ДОБАВЬТЕ ДЛЯ КОММЕНТАРИЕВ В MR ↓↓↓
        -Dsonar.gitlab.url=https://gitlab.nikitapcl.ru \
        -Dsonar.gitlab.user_token=${GITLAB_TOKEN} \
        -Dsonar.gitlab.project_id=${CI_PROJECT_ID} \
        -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} \
        -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME} \
        -Dsonar.gitlab.max_global_issues=50 \
        -Dsonar.gitlab.unique_issue_per_inline=true \
        -Dsonar.gitlab.failure_notification_mode=exit-code \
  allow_failure: false 
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'
  tags:
    - sonar
#ДОБАВИТЬ СБОРКУ
stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - oscript ./scripts/edt_build.os
  artifacts:
    untracked: true
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - "artifacts/*.cf*"
